CREATE DATABASE [Datos_Taller]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Datos_Taller', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Datos_Taller.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Datos_Taller_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Datos_Taller_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 WITH LEDGER = OFF
GO
ALTER DATABASE [Datos_Taller] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Datos_Taller] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Datos_Taller] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Datos_Taller] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Datos_Taller] SET ARITHABORT OFF 
GO
ALTER DATABASE [Datos_Taller] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Datos_Taller] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Datos_Taller] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Datos_Taller] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Datos_Taller] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Datos_Taller] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Datos_Taller] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Datos_Taller] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Datos_Taller] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Datos_Taller] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Datos_Taller] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Datos_Taller] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Datos_Taller] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Datos_Taller] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Datos_Taller] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Datos_Taller] SET  READ_WRITE 
GO
ALTER DATABASE [Datos_Taller] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Datos_Taller] SET  MULTI_USER 
GO
ALTER DATABASE [Datos_Taller] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Datos_Taller] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Datos_Taller] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Datos_Taller]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Datos_Taller]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Datos_Taller] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
